name: gdrive_uploader release action

on:
  push:
    branches:
      - master

jobs:
  release_action:
    name: gdrive_uploader release action
    runs-on: ubuntu-latest
    container:
      image: golang:1.15.5
    steps:
    - name: Update & install packages
      run: |
        apt-get -qq update
    - name: Check out code
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0
    - name: Release binary
      if: github.ref == 'refs/heads/master'
      env:
        GITHUB_API: ${{ secrets.RELEASE_API }}
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      run: |
        make release
